
/* Drop Triggers */

DROP TRIGGER TRI_CATEGORY_INFO_CATE_NUM;
DROP TRIGGER TRI_CONTRACT_INFO_CONT_NUM;
DROP TRIGGER TRI_CREER_INFO_CRR_NUM;
DROP TRIGGER TRI_CRITIC_INFO_CRT_NUM;
DROP TRIGGER TRI_PJBODY_INFO_PJB_NUM;
DROP TRIGGER TRI_PJHEAD_INFO_PJH_NUM;
DROP TRIGGER TRI_UPDATE_INFO_UP_NUM;
DROP TRIGGER TRI_USER_INFO_UI_NUM;



/* Drop Tables */

DROP TABLE CONTRACT_INFO CASCADE CONSTRAINTS;
DROP TABLE CRITIC_INFO CASCADE CONSTRAINTS;
DROP TABLE PJBODY_INFO CASCADE CONSTRAINTS;
DROP TABLE UPDATE_INFO CASCADE CONSTRAINTS;
DROP TABLE PJHEAD_INFO CASCADE CONSTRAINTS;
DROP TABLE CATEGORY_INFO CASCADE CONSTRAINTS;
DROP TABLE CREER_INFO CASCADE CONSTRAINTS;
DROP TABLE USER_INFO CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_CATEGORY_INFO_CATE_NUM;
DROP SEQUENCE SEQ_CONTRACT_INFO_CONT_NUM;
DROP SEQUENCE SEQ_CREER_INFO_CRR_NUM;
DROP SEQUENCE SEQ_CRITIC_INFO_CRT_NUM;
DROP SEQUENCE SEQ_PJBODY_INFO_PJB_NUM;
DROP SEQUENCE SEQ_PJHEAD_INFO_PJH_NUM;
DROP SEQUENCE SEQ_UPDATE_INFO_UP_NUM;
DROP SEQUENCE SEQ_USER_INFO_UI_NUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_CATEGORY_INFO_CATE_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CONTRACT_INFO_CONT_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CREER_INFO_CRR_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CRITIC_INFO_CRT_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PJBODY_INFO_PJB_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PJHEAD_INFO_PJH_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_UPDATE_INFO_UP_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_USER_INFO_UI_NUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE CATEGORY_INFO
(
	-- 카테고리 번호
	CATE_NUM number NOT NULL UNIQUE,
	-- 카테고리 코드
	CATE_CODE char(6) NOT NULL UNIQUE,
	-- 카테고리 종류
	CATE_NAME varchar2(30) NOT NULL UNIQUE,
	-- 카테고리 설명
	CATE_DESC char(100),
	PRIMARY KEY (CATE_NUM)
);


CREATE TABLE CONTRACT_INFO
(
	-- 구직신청 댓글 PK
	CONT_NUM number NOT NULL UNIQUE,
	-- 회원정보 PK
	UI_NUM number NOT NULL,
	-- 구직자 정보 PK
	CRR_NUM number NOT NULL,
	-- 프로젝트 헤드 PK
	PJH_NUM number NOT NULL,
	-- 구직 댓글 작성일자
	CONT_CREDAT date NOT NULL,
	-- 구직신청 댓글 본문
	CONT_TEXT varchar2(3000),
	PRIMARY KEY (CONT_NUM)
);


CREATE TABLE CREER_INFO
(
	-- 구직자 정보 PK
	CRR_NUM number NOT NULL UNIQUE,
	-- 회원정보 PK
	UI_NUM number NOT NULL,
	-- 구직자 이름
	CRR_NAME varchar2(20) NOT NULL,
	-- 구직자 나이
	CRR_AGE number(2,0) NOT NULL,
	-- 거주지 주소 간단히
	CRR_ADDR varchar2(30) NOT NULL,
	-- 직업 직군
	CRR_JOB varchar2(30) NOT NULL,
	-- 경험 분야
	CRR_EXP varchar2(300) NOT NULL,
	-- 커리어 본문
	CRR_DESC varchar2(1000) NOT NULL,
	PRIMARY KEY (CRR_NUM)
);


CREATE TABLE CRITIC_INFO
(
	-- 댓글 데이터 PK
	CRT_NUM number NOT NULL UNIQUE,
	-- 프로젝트 헤더 PK
	PJH_NUM number NOT NULL,
	-- 댓글 작성회원 정보 PK
	UI_NUM number NOT NULL,
	-- 댓글작성일자
	CRT_CREDAT date NOT NULL,
	-- 댓글 제목
	CRT_TITLE varchar2(100) NOT NULL,
	-- CRT_TEXT
	CRT_TEXT varchar2(3000) NOT NULL,
	-- 수익성평점
	CRT_PROFITSCORE number DEFAULT 0 NOT NULL,
	-- 안정성 평점
	CRT_STABLESCORE number DEFAULT 0 NOT NULL,
	-- 독창성 평점
	CRT_ORIGINSCORE number DEFAULT 0 NOT NULL,
	PRIMARY KEY (CRT_NUM)
);


CREATE TABLE PJBODY_INFO
(
	-- 프로젝트 바디 정보 PK
	PJB_NUM number NOT NULL UNIQUE,
	-- 내용 구성할 프로젝트의 PK
	PJH_NUM number NOT NULL,
	--  1: STORY HTML, 2~4:각각 요약 #1 ~ #3
	PJB_LEVEL number NOT NULL,
	-- 레벨에 따른 타이틀 제목
	PJB_TITLE varchar2(200) NOT NULL,
	--  PJH_LEVEL=1일때는 STORY 내용 HTML
	PJB_TEXT varchar2(1000) NOT NULL,
	PRIMARY KEY (PJB_NUM)
);


CREATE TABLE PJHEAD_INFO
(
	-- 프로젝트 헤드 PK
	PJH_NUM number NOT NULL UNIQUE,
	-- 사용자 정보 외래키
	UI_NUM number NOT NULL,
	-- 카테고리 코드
	CATE_CODE char(6) NOT NULL,
	-- 프로젝트 캐치프레이즈
	PJH_INTRO varchar2(100) NOT NULL,
	-- 프로젝트 이름
	PJH_NAME varchar2(30) NOT NULL,
	-- 프로젝트 이미지 경로
	PJH_IMG varchar2(150) NOT NULL,
	-- 제안 시작 일자
	PJH_STARTDAT date NOT NULL,
	-- 제안 종료 일자
	PJH_ENDDAT date,
	-- 프로젝트 목표 투자금
	PJH_GOALMONEY number DEFAULT 0 NOT NULL,
	-- 프로젝트 현재 투자금
	PJH_NOWMONEY number DEFAULT 0 NOT NULL,
	-- 평가 총 합 평균
	PJH_CRITICSUM number DEFAULT 0 NOT NULL,
	-- 프로젝트 좋아요 개수
	PJH_LOVIT number DEFAULT 0 NOT NULL,
	-- 프로젝트 진행 상태
	PJH_STATUS number NOT NULL,
	PRIMARY KEY (PJH_NUM)
);


CREATE TABLE UPDATE_INFO
(
	-- 댓글 데이터 PK
	UP_NUM number NOT NULL UNIQUE,
	-- 작성회원 정보 PK
	UI_NUM number NOT NULL,
	-- 해당 프로젝트 PK
	PJH_NUM number NOT NULL,
	-- 업데이트 작성일자
	UP_CREDAT date NOT NULL,
	-- 업데이트 요약 이미지
	UP_IMG varchar2(150),
	-- 업데이트 제목
	UP_TITLE varchar2(100) NOT NULL,
	-- 업데이트 본문
	UP_TEXT varchar2(3000) NOT NULL,
	PRIMARY KEY (UP_NUM)
);


CREATE TABLE USER_INFO
(
	-- 회원정보 PK
	UI_NUM number NOT NULL UNIQUE,
	-- kakao email
	UI_EMAIL varchar2(40) NOT NULL UNIQUE,
	-- API 발급 고유 ID
	UI_ID number NOT NULL UNIQUE,
	-- kakao nickname
	UI_NAME varchar2(60) NOT NULL,
	-- kakao image
	UI_IMG varchar2(150),
	-- 유저 권한 레벨
	UI_LEVEL number DEFAULT 1 NOT NULL UNIQUE,
	-- 보유금액
	UI_PREFUND number DEFAULT 0 NOT NULL,
	PRIMARY KEY (UI_NUM)
);



/* Create Foreign Keys */

ALTER TABLE PJHEAD_INFO
	ADD FOREIGN KEY (CATE_CODE)
	REFERENCES CATEGORY_INFO (CATE_CODE)
;


ALTER TABLE CONTRACT_INFO
	ADD FOREIGN KEY (CRR_NUM)
	REFERENCES CREER_INFO (CRR_NUM)
;


ALTER TABLE CONTRACT_INFO
	ADD FOREIGN KEY (PJH_NUM)
	REFERENCES PJHEAD_INFO (PJH_NUM)
;


ALTER TABLE CRITIC_INFO
	ADD FOREIGN KEY (PJH_NUM)
	REFERENCES PJHEAD_INFO (PJH_NUM)
;


ALTER TABLE PJBODY_INFO
	ADD FOREIGN KEY (PJH_NUM)
	REFERENCES PJHEAD_INFO (PJH_NUM)
;


ALTER TABLE UPDATE_INFO
	ADD FOREIGN KEY (PJH_NUM)
	REFERENCES PJHEAD_INFO (PJH_NUM)
;


ALTER TABLE CONTRACT_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
;


ALTER TABLE CREER_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
;


ALTER TABLE CRITIC_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
;


ALTER TABLE PJHEAD_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
;


ALTER TABLE UPDATE_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_CATEGORY_INFO_CATE_NUM BEFORE INSERT ON CATEGORY_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_CATEGORY_INFO_CATE_NUM.nextval
	INTO :new.CATE_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_CONTRACT_INFO_CONT_NUM BEFORE INSERT ON CONTRACT_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_CONTRACT_INFO_CONT_NUM.nextval
	INTO :new.CONT_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_CREER_INFO_CRR_NUM BEFORE INSERT ON CREER_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_CREER_INFO_CRR_NUM.nextval
	INTO :new.CRR_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_CRITIC_INFO_CRT_NUM BEFORE INSERT ON CRITIC_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_CRITIC_INFO_CRT_NUM.nextval
	INTO :new.CRT_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PJBODY_INFO_PJB_NUM BEFORE INSERT ON PJBODY_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_PJBODY_INFO_PJB_NUM.nextval
	INTO :new.PJB_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PJHEAD_INFO_PJH_NUM BEFORE INSERT ON PJHEAD_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_PJHEAD_INFO_PJH_NUM.nextval
	INTO :new.PJH_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_UPDATE_INFO_UP_NUM BEFORE INSERT ON UPDATE_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_UPDATE_INFO_UP_NUM.nextval
	INTO :new.UP_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_USER_INFO_UI_NUM BEFORE INSERT ON USER_INFO
FOR EACH ROW
BEGIN
	SELECT SEQ_USER_INFO_UI_NUM.nextval
	INTO :new.UI_NUM
	FROM dual;
END;

/




/* Comments */

COMMENT ON COLUMN CATEGORY_INFO.CATE_NUM IS '카테고리 번호';
COMMENT ON COLUMN CATEGORY_INFO.CATE_CODE IS '카테고리 코드';
COMMENT ON COLUMN CATEGORY_INFO.CATE_NAME IS '카테고리 종류';
COMMENT ON COLUMN CATEGORY_INFO.CATE_DESC IS '카테고리 설명';
COMMENT ON COLUMN CONTRACT_INFO.CONT_NUM IS '구직신청 댓글 PK';
COMMENT ON COLUMN CONTRACT_INFO.UI_NUM IS '회원정보 PK';
COMMENT ON COLUMN CONTRACT_INFO.CRR_NUM IS '구직자 정보 PK';
COMMENT ON COLUMN CONTRACT_INFO.PJH_NUM IS '프로젝트 헤드 PK';
COMMENT ON COLUMN CONTRACT_INFO.CONT_CREDAT IS '구직 댓글 작성일자';
COMMENT ON COLUMN CONTRACT_INFO.CONT_TEXT IS '구직신청 댓글 본문';
COMMENT ON COLUMN CREER_INFO.CRR_NUM IS '구직자 정보 PK';
COMMENT ON COLUMN CREER_INFO.UI_NUM IS '회원정보 PK';
COMMENT ON COLUMN CREER_INFO.CRR_NAME IS '구직자 이름';
COMMENT ON COLUMN CREER_INFO.CRR_AGE IS '구직자 나이';
COMMENT ON COLUMN CREER_INFO.CRR_ADDR IS '거주지 주소 간단히';
COMMENT ON COLUMN CREER_INFO.CRR_JOB IS '직업 직군';
COMMENT ON COLUMN CREER_INFO.CRR_EXP IS '경험 분야';
COMMENT ON COLUMN CREER_INFO.CRR_DESC IS '커리어 본문';
COMMENT ON COLUMN CRITIC_INFO.CRT_NUM IS '댓글 데이터 PK';
COMMENT ON COLUMN CRITIC_INFO.PJH_NUM IS '프로젝트 헤더 PK';
COMMENT ON COLUMN CRITIC_INFO.UI_NUM IS '댓글 작성회원 정보 PK';
COMMENT ON COLUMN CRITIC_INFO.CRT_CREDAT IS '댓글작성일자';
COMMENT ON COLUMN CRITIC_INFO.CRT_TITLE IS '댓글 제목';
COMMENT ON COLUMN CRITIC_INFO.CRT_TEXT IS 'CRT_TEXT';
COMMENT ON COLUMN CRITIC_INFO.CRT_PROFITSCORE IS '수익성평점';
COMMENT ON COLUMN CRITIC_INFO.CRT_STABLESCORE IS '안정성 평점';
COMMENT ON COLUMN CRITIC_INFO.CRT_ORIGINSCORE IS '독창성 평점';
COMMENT ON COLUMN PJBODY_INFO.PJB_NUM IS '프로젝트 바디 정보 PK';
COMMENT ON COLUMN PJBODY_INFO.PJH_NUM IS '내용 구성할 프로젝트의 PK';
COMMENT ON COLUMN PJBODY_INFO.PJB_LEVEL IS ' 1: STORY HTML, 2~4:각각 요약 #1 ~ #3';
COMMENT ON COLUMN PJBODY_INFO.PJB_TITLE IS '레벨에 따른 타이틀 제목';
COMMENT ON COLUMN PJBODY_INFO.PJB_TEXT IS ' PJH_LEVEL=1일때는 STORY 내용 HTML';
COMMENT ON COLUMN PJHEAD_INFO.PJH_NUM IS '프로젝트 헤드 PK';
COMMENT ON COLUMN PJHEAD_INFO.UI_NUM IS '사용자 정보 외래키';
COMMENT ON COLUMN PJHEAD_INFO.CATE_CODE IS '카테고리 코드';
COMMENT ON COLUMN PJHEAD_INFO.PJH_INTRO IS '프로젝트 캐치프레이즈';
COMMENT ON COLUMN PJHEAD_INFO.PJH_NAME IS '프로젝트 이름';
COMMENT ON COLUMN PJHEAD_INFO.PJH_IMG IS '프로젝트 이미지 경로';
COMMENT ON COLUMN PJHEAD_INFO.PJH_STARTDAT IS '제안 시작 일자';
COMMENT ON COLUMN PJHEAD_INFO.PJH_ENDDAT IS '제안 종료 일자';
COMMENT ON COLUMN PJHEAD_INFO.PJH_GOALMONEY IS '프로젝트 목표 투자금';
COMMENT ON COLUMN PJHEAD_INFO.PJH_NOWMONEY IS '프로젝트 현재 투자금';
COMMENT ON COLUMN PJHEAD_INFO.PJH_CRITICSUM IS '평가 총 합 평균';
COMMENT ON COLUMN PJHEAD_INFO.PJH_LOVIT IS '프로젝트 좋아요 개수';
COMMENT ON COLUMN PJHEAD_INFO.PJH_STATUS IS '프로젝트 진행 상태';
COMMENT ON COLUMN UPDATE_INFO.UP_NUM IS '댓글 데이터 PK';
COMMENT ON COLUMN UPDATE_INFO.UI_NUM IS '작성회원 정보 PK';
COMMENT ON COLUMN UPDATE_INFO.PJH_NUM IS '해당 프로젝트 PK';
COMMENT ON COLUMN UPDATE_INFO.UP_CREDAT IS '업데이트 작성일자';
COMMENT ON COLUMN UPDATE_INFO.UP_IMG IS '업데이트 요약 이미지';
COMMENT ON COLUMN UPDATE_INFO.UP_TITLE IS '업데이트 제목';
COMMENT ON COLUMN UPDATE_INFO.UP_TEXT IS '업데이트 본문';
COMMENT ON COLUMN USER_INFO.UI_NUM IS '회원정보 PK';
COMMENT ON COLUMN USER_INFO.UI_EMAIL IS 'kakao email';
COMMENT ON COLUMN USER_INFO.UI_ID IS 'API 발급 고유 ID';
COMMENT ON COLUMN USER_INFO.UI_NAME IS 'kakao nickname';
COMMENT ON COLUMN USER_INFO.UI_IMG IS 'kakao image';
COMMENT ON COLUMN USER_INFO.UI_LEVEL IS '유저 권한 레벨';
COMMENT ON COLUMN USER_INFO.UI_PREFUND IS '보유금액';



